# Generated by Django 5.0.1 on 2024-06-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_commentary_votes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentary_text',
            new_name='comment_text',
        ),
    ]
